基底クラスを追加
m-Mons/MittaUI pull request #42
Opened 2024-05-11 03:57 UTC by mittan1330

2024-05-11 08:57 UTC, AtaruMatsudaira requested changes
ディレクトリ的にはAssets/Sandbox/mittan/配下にあるといいかなぁ

2024-05-11 15:31 UTC, AtaruMatsudaira requested changes
#49 や #48 と被ってる？？？

2024-05-11 15:46 UTC, mittan1330 commented
ここから#48と#49が派生してた！
プルリクの出し方が悪かったかも。。。すまぬ〜

2024-05-12 06:55 UTC, AtaruMatsudaira requested changes
こめんちょ

2024-05-12 06:55 UTC, AtaruMatsudaira commented on Assets/Scripts/MittaUI.Sample.asmdef
これは要らないかも？

2024-05-12 23:25 UTC, merged