toggleの実装
m-Mons/MittaUI pull request #8
Opened 2024-05-06 17:28 UTC by AtaruMatsudaira

これが含まれてるので、マージされてから読むべし
https://github.com/m-Mons/MittaUI/pull/6

2024-05-06 23:34 UTC, mittan1330 approved these changes
コメントしたけど、良さそう！

2024-05-06 23:34 UTC, mittan1330 commented on MittaUI.Runtime/TweenProvider/TweenProvider.cs
> +namespace MittaUI.Runtime.TinyTween
https://github.com/m-Mons/MittaUI/pull/6/files
このプルリクと内容被ってるかも？？

2024-05-07 00:31 UTC, ItoSeiy requested changes
コメントについて見てもらいたい！
あとは動作確認出来てればOK(でんしゃのなかだからできん、、、、)

2024-05-07 00:31 UTC, ItoSeiy commented on MittaUI.Runtime/Parts/BaseToggleButton.cs
> +    [RequireComponent(typeof(SimpleButton))]
フィールドでBaseButtonw定義してるのは凄く良くて、ここでSimpleButtonをRequireしてるのは微妙かも？

2024-05-07 00:33 UTC, AtaruMatsudaira commented on MittaUI.Runtime/Parts/BaseToggleButton.cs
> +    [RequireComponent(typeof(SimpleButton))]
何でそんな実装してたんだ…🤔
修正しやす

2024-05-07 02:08 UTC, AtaruMatsudaira commented on MittaUI.Runtime/TweenProvider/TweenProvider.cs
> +namespace MittaUI.Runtime.TinyTween
その作業ブランチから派生させて作業せざるを得なくて...
もうそのPRはMergeされたから気にしなくてOK

2024-05-07 04:55 UTC, merged